# Generated by Django 2.2 on 2019-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('town_code', models.IntegerField()),
                ('department_code', models.IntegerField()),
                ('population', models.IntegerField()),
            ],
        ),
    ]
